# ========= Development ========= # 
compose-build:
	docker-compose -p climb-ai build app

compose-up:
	docker-compose -p climb-ai up --build app

compose-run:
	docker-compose -p climb-ai up app

compose-down:
	docker-compose -p climb-ai down
